name: 🪟 Windows Exports Tests
on:
  workflow_call:
    inputs:
      godot-version:
        type: string
      jvm-version:
        type: string

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows_exports_tests
  cancel-in-progress: true

jobs:
  test-windows-exports:
    runs-on: windows-latest
    name: ${{ matrix.name }}
    strategy:
      matrix:
        include:
          - name: dev tests
            target: dev
            bootstrap-target: debug
            jvm: jvm
          - name: release tests
            target: release
            bootstrap-target: release
            jvm: jvm
          - name: dev tests graal native image
            target: dev
            bootstrap-target: debug
            jvm: native-image
          - name: release tests graal native image
            target: release
            bootstrap-target: release
            jvm: native-image

    steps:
      - name: Clone Godot Engine
        uses: actions/checkout@v4
        with:
          repository: godotengine/godot
          ref: ${{ inputs.godot-version }}

      - name: Clone Godot JVM module.
        uses: actions/checkout@v4
        with:
          path: modules/kotlin_jvm

      - uses: actions/setup-java@v4
        if: matrix.jvm  == 'jvm'
        with:
          distribution: adopt-hotspot
          java-version: ${{ inputs.jvm-version }}

      - uses: graalvm/setup-graalvm@v1
        if: matrix.jvm  == 'native-image'
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/master' }}

      - name: Download windows editor ${{ matrix.target }}
        uses: actions/download-artifact@v4
        with:
          name: editor_${{ matrix.target }}_windows_x86_64
          path: './bin'

      - name: Download godot-bootstrap ${{ matrix.bootstrap-target }}
        uses: actions/download-artifact@v4
        with:
          name: jvm_godot-bootstrap_${{ matrix.bootstrap-target }}
          path: './bin'

      - name: Download windows x86_64 ${{ matrix.bootstrap-target }} export template
        uses: actions/download-artifact@v4
        with:
          name: export_template_${{ matrix.bootstrap-target }}_windows_x86_64
          path: "./"

      - name: Set build parameters
        if: matrix.jvm  == 'jvm'
        run: |
          buildParams = ""

      - name: Set build parameters
        if: matrix.jvm  == 'native-image'
        run: |
          buildParams = "-PgraalExport=true"

      - name: Prepare export
        run: |
          mkdir -p modules/kotlin_jvm/harness/tests/export
          mv godot.windows.template_${{ matrix.bootstrap-target }}.x86_64.exe modules/kotlin_jvm/harness/tests/godot.windows.template_${{ matrix.bootstrap-target }}.x86_64.exe

      - name: Build tests project
        run: |
          modules/kotlin_jvm/harness/tests/gradlew -p modules/kotlin_jvm/harness/tests/ build -P${{ matrix.bootstrap-target }} $buildParams

      - name: Create JRE
        run: |
          cd modules/kotlin_jvm/harness/tests/
          jlink --add-modules java.base,java.logging --output jre-amd64-windows

      - name: Export tests debug
        if: ${{ matrix.bootstrap-target == 'debug' }}
        run: |
          cd modules/kotlin_jvm/harness/tests/
          ./gradlew exportDebug $buildParams
        timeout-minutes: 30

      - name: Export tests release
        if: ${{ matrix.bootstrap-target == 'release' }}
        run: |
          cd modules/kotlin_jvm/harness/tests/
          ./gradlew exportRelease $buildParams
        timeout-minutes: 30

      - name: Run Tests
        run: |
          cd modules/kotlin_jvm/harness/tests/
          ./gradlew runExportedGutTests
        timeout-minutes: 30
