name: Dev build and test

on:
  push:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!master'   # excludes master

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-trigger_dev
  cancel-in-progress: true

jobs:
  setup-build-variables:
    # Fake job to define outputs which can be used in the other jobs
    name: 🛠️ Setup build variables
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' # do not run on pull requests. It seems we cannot set this on the whole workflow, hence we set it on the individual steps instead...
    steps:
      - run: |
          echo "Setup done"
    outputs: # defined here explicitly, so it only needs to be defined here. All other workflows can just reference it
      godot-kotlin-jvm-version: "0.8.3-4.2.1"
      godot-version: "4.2.1-stable"
      jvm-version: "17"

  build-jvm:
    name: ☕ Build Jvm
    uses: ./.github/workflows/build_jvm.yml
    if: github.event_name != 'pull_request' # do not run on pull requests. It seems we cannot set this on the whole workflow, hence we set it on the individual steps instead...
    needs:
      - setup-build-variables
    with:
      godot-version: ${{ needs.setup-build-variables.outputs['godot-version'] }}
      jvm-version: ${{ needs.setup-build-variables.outputs['jvm-version'] }}

  build-linux:
    name: 🐧 Build Linux
    uses: ./.github/workflows/build_linux.yml
    if: github.event_name != 'pull_request' # do not run on pull requests. It seems we cannot set this on the whole workflow, hence we set it on the individual steps instead...
    needs:
      - setup-build-variables
    with:
      godot-version: ${{ needs.setup-build-variables.outputs['godot-version'] }}

  assemble-linux:
    name: 🐧 Assemble linux
    uses: ./.github/workflows/assemble_linux.yml
    if: github.event_name != 'pull_request' # do not run on pull requests. It seems we cannot set this on the whole workflow, hence we set it on the individual steps instead...
    needs:
      - setup-build-variables
      - build-jvm
      - build-linux
    with:
      godot-kotlin-jvm-version: ${{ needs.setup-build-variables.outputs['godot-kotlin-jvm-version'] }}
      godot-version: ${{ needs.setup-build-variables.outputs['godot-version'] }}

  test-linux:
    name: 🐧 Test Linux
    uses: ./.github/workflows/test_linux.yml
    if: github.event_name != 'pull_request' # do not run on pull requests. It seems we cannot set this on the whole workflow, hence we set it on the individual steps instead...
    needs:
      - setup-build-variables
      - build-jvm
      - build-linux
    with:
      godot-version: ${{ needs.setup-build-variables.outputs['godot-version'] }}
      jvm-version: ${{ needs.setup-build-variables.outputs['jvm-version'] }}
